// Generated by CoffeeScript 1.6.3
(function() {
  this.Analyze = function() {
    var extractKeyword;
    ({
      constructor: function(contents) {
        console.log("analyxr@");
        return extractKeyword(contents);
      }
    });
    return extractKeyword = function(contents) {
      var segmenter, words;
      segmenter = new TinySegmenter();
      words = segmenter.segment(contents);
      return console.log(words);
    };
  };

}).call(this);
