// Generated by CoffeeScript 1.6.3
(function() {
  this.FeelingValue = (function() {
    var allSame;

    function FeelingValue() {}

    FeelingValue.constructor = function() {
      return this.filter = 0;
    };

    FeelingValue.prototype.calcValueFromString = function(text) {
      var data, feeling_value, i, samelen, segmenter, v, word, words, _i, _j, _k, _len, _len1;
      segmenter = new TinySegmenter();
      words = segmenter.segment(text);
      console.log(words);
      feeling_value = {
        plus: [0, 0, 0, 0, 0, 0, 0],
        minus: [0, 0, 0, 0, 0, 0, 0]
      };
      this.filter = 0;
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        if (word.match(/激しい/)) {
          this.filter = 1;
        }
        data = feeling[word];
        samelen = allSame(word);
        if (samelen > 0) {
          for (i = _j = 0; _j <= 6; i = ++_j) {
            feeling_value.plus[i] += samelen;
          }
          continue;
        }
        if (data) {
          for (i = _k = 0, _len1 = data.length; _k < _len1; i = ++_k) {
            v = data[i];
            if (v > 0.0003) {
              feeling_value.plus[i]++;
            }
            if (v < -0.0003) {
              feeling_value.minus[i]++;
            }
          }
        }
      }
      console.log(feeling_value.plus, feeling_value.minus);
      return feeling_value;
    };

    allSame = function(word) {
      var first, w, _i, _len;
      first = word[0];
      for (_i = 0, _len = word.length; _i < _len; _i++) {
        w = word[_i];
        if (w !== first) {
          return 0;
        }
      }
      return word.length;
    };

    return FeelingValue;

  })();

}).call(this);
